version: "3"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: "Abcd1234"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_AGENT_ENABLED: true
      TZ: America/Sao_Paulo
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-Usa", "-PAbcd1234", "-Q", "select 1"]
      interval: 1s
      retries: 50

  mssqltools:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      sqlserver:
        condition: service_healthy
    volumes:
      - ./init.sql:/tmp/init.sql
    command: /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P Abcd1234 -i /tmp/init.sql